export const SPORTS_VENUE_MAP: Record<string, string> = {
  "cricket": "Turf",
  "box-cricket": "Turf",
  "tennis-ball-cricket": "Turf",
  "football": "Ground",
  "futsal": "Court",
  "badminton": "Court",
  "tennis": "Court",
  "soft-tennis": "Court",
  "pickleball": "Court",
  "padel": "Court",
  "squash": "Court",
  "racquetball": "Court",
  "basketball": "Court",
  "3x3-basketball": "Court",
  "volleyball": "Court",
  "beach-volleyball": "Court",
  "handball": "Court",
  "kabaddi": "Ground",
  "beach-kabaddi": "Ground",
  "circle-kabaddi": "Ground",
  "kho-kho": "Ground",
  "hockey": "Ground",
  "field-hockey": "Ground",
  "rugby": "Ground",
  "american-football": "Ground",
  "baseball": "Ground",
  "softball": "Ground",
  "athletics": "Track",
  "cycling": "Track",
  "track-cycling": "Velodrome",
  "skating": "Rink",
  "roller-skating": "Rink",
  "ice-skating": "Rink",
  "ice-hockey": "Rink",
  "swimming": "Pool",
  "water-polo": "Pool",
  "diving": "Pool",
  "artistic-swimming": "Pool",
  "table-tennis": "Table",
  "billiards": "Table",
  "snooker": "Table",
  "pool": "Table",
  "carrom": "Board",
  "chess": "Table",
  "archery": "Range",
  "shooting": "Range",
  "boxing": "Ring",
  "kickboxing": "Ring",
  "wrestling": "Arena",
  "judo": "Dojo",
  "karate": "Dojo",
  "taekwondo": "Dojo",
  "wushu": "Arena",
  "fencing": "Piste",
  "gymnastics": "Arena",
  "yoga": "Studio",
  "yogasana": "Studio",
  "pilates": "Studio",
  "dance": "Studio",
  "fitness": "Gym",
  "gym": "Gym",
  "golf": "Course",
  "mini-golf": "Course",
  "polo": "Ground",
  "equestrian": "Arena",
  "horse-riding": "Arena",
  "rowing": "Water Course",
  "kayaking": "Water Course",
  "canoeing": "Water Course",
  "surfing": "Beach",
  "sailing": "Water Course",
  "yachting": "Marina",
  "triathlon": "Course",
  "modern-pentathlon": "Arena",
  "sepaktakraw": "Court",
  "netball": "Court",
  "korfball": "Court",
  "throwball": "Court",
  "roll-ball": "Court",
  "shooting-ball": "Court",
  "atya-patya": "Ground",
  "mallakhamb": "Arena",
  "powerlifting": "Gym",
  "weightlifting": "Gym",
  "bodybuilding": "Gym",
  "tug-of-war": "Ground",
  "bridge": "Table",
  "bowling": "Lane",
  "ten-pin-bowling": "Lane",
  "darts": "Board",
  "air-hockey": "Table",
  "foosball": "Table",
  "paintball": "Arena",
  "laser-tag": "Arena",
  "climbing": "Climbing Wall",
  "bouldering": "Climbing Wall",
  "martial-arts": "Dojo",
  "aikido": "Dojo",
  "jiu-jitsu": "Dojo",
  "muay-thai": "Ring",
  "mma": "Arena",
  "wushu-sanda": "Ring",
  "flying-disc": "Ground",
  "ultimate-frisbee": "Ground",
  "base-jumping": "Outdoor Site",
  "skateboarding": "Skate Park",
  "bmx": "Track",
  "motorsport": "Circuit",
  "karting": "Circuit",
  "drag-racing": "Track",
  "air-sports": "Airfield",
  "paragliding": "Launch Site",
  "hang-gliding": "Launch Site",
  "triathlon-swimming": "Pool"
};
